spring.application.name=mini-ecommerce
server.port=8080

# H2 In-Memory DB
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Always init schema from SQL
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:scripts/schema.sql
spring.sql.init.data-locations=classpath:scripts/data.sql

# Prevent Hibernate from auto-creating schema
spring.jpa.hibernate.ddl-auto=validate

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.ecommerce=DEBUG

# springdoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs

# Naming strategy to preserve exact names from annotations/schema
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
